"""
Narration script for: semi-prime-factorization
Generated: 2026-02-13
Duration: ~240 seconds
"""

SCRIPT = {
    "intro": """Welcome to our exploration of semi-prime numbers. A semi-prime, also known as a 2-almost prime, is a natural number that is the product of exactly two prime numbers. For example, 4 is 2 times 2, 6 is 2 times 3, and 9 is 3 times 3. Unlike prime numbers which have no positive divisors other than one and themselves, semi-primes have exactly two prime factors counting multiplicity. This makes them the simplest composite numbers and an important class in number theory.""",
    "properties": """Semi-primes have some fascinating properties that make them special in mathematics. Every semi-prime is square-free if its prime factors are distinct, like 15 which is 3 times 5. But square semi-primes like 4 or 9 have repeated prime factors. The smallest semi-primes are 4, 6, 9, 10, and 14. Semi-primes are always even unless one factor is 2, and they play a key role in cryptography and factoring algorithms. These numbers bridge the gap between primes and more complex composites.""",
    "identification": """To identify if a number is semi-prime, we can use trial division, a systematic method that works well for these numbers. First, check if the number is prime itself - if it is, it's not semi-prime. Then, divide by small primes starting from 2. If you find exactly two prime factors, it's semi-prime. For example, to check 15: divide by 2 - no, by 3 - yes, you get 5, which is also prime. So 15 equals 3 times 5, making it semi-prime. For larger numbers, we can optimize by only checking primes up to the square root of the number, since any larger factor would need a smaller counterpart.""",
    "factorization": """Factorizing semi-primes is straightforward since they have only two prime factors, but the methods we use have broader applications. Trial division works well for small numbers - for example, to factor 21: try dividing by 3, you get 7. So 21 equals 3 times 7. For larger semi-primes, we can use more sophisticated methods like Pollard's rho algorithm or even quantum algorithms like Shor's. Semi-primes are particularly important in cryptography because the difficulty of factoring large semi-primes forms the basis for RSA encryption security. Understanding these factorization techniques helps us appreciate both the beauty and the utility of number theory.""",
    "conclusion": """In summary, semi-prime numbers are the product of exactly two primes, forming the essential bridge between prime numbers and more complex composites. We've explored their definition, key properties, identification methods, and factorization techniques. These numbers aren't just mathematical curiosities - they play crucial roles in cryptography, computational number theory, and our understanding of prime distribution. Whether you're fascinated by pure mathematics or working on secure digital communications, semi-primes offer rich insights into the elegant structure of the number system. Thank you for joining this exploration of semi-prime factorization.""",
}
