"""
Narration script for: AI Analysis of Epstein Files Redactions and Accountability Failures
Generated: 2026-02-11
Duration: ~600 seconds
"""

SCRIPT = {
    "intro": """Welcome to this in-depth analysis of the Epstein files redactions, where we'll use insights from multiple AI models to uncover what really happened. The Epstein Files Transparency Act of 2025 required the DOJ to release all documents within 30 days, but instead, we saw selective redactions that protected powerful figures while exposing victims. We'll look at where models like Claude, Kimi, and Grok agree, where they differ, and their unique findings. Let's dive in.""",
    "agreements": """All three AI models converged on several key points. First, the redaction of Les Wexner's name as a co-conspirator was surgically precise – his name appeared over 4,000 times elsewhere, but the one critical designation was scrubbed. This wasn't random; it was targeted. Second, the correction only happened after Rep. Massie's confrontation, not through proactive review. Third, AG Bondi's personal attack on Massie as having 'Trump Derangement Syndrome' was a deflection tactic when accountability was demanded. Most disturbingly, child victims' identities were exposed in thousands of documents, while powerful co-conspirators were shielded – a complete inversion of priorities. The DOJ also failed to meet the 30-day deadline, and Bondi couldn't name anyone responsible for these failures.""",
    "disagreements": """While the models agreed on the patterns, they differed on interpretation. Claude saw it as intentional design – 'not dysfunction, but function.' Kimi suggested targeted actions with some room for inertia, while Grok emphasized structural failures without committing to conspiracy. Claude highlighted the committee chairman siding with Bondi as oversight capture, and Grok uniquely pointed out the FBI's pre-redaction role as a separate suppression layer.""",
    "unique": """Each model brought unique insights. Claude discovered Wexner's condemnation letter came just two days before Epstein's death and noted their deep financial ties, undermining the victim narrative. Kimi highlighted how the quick 40-minute fix showed DOJ could act fast but chose not to until caught. Grok revealed the FBI redacted documents before sending to DOJ, creating an untraceable dual-layer system perfect for deniability.""",
    "analysis": """Putting it all together, the selective Wexner redaction is the highest-confidence finding, showing awareness of legal differences between association and conspiracy. The victim exposure versus elite protection defies coincidence, suggesting the system is built to shield power. Divergences point to needed reforms – if intentional, we need accountability; if structural, better laws. The FBI-DOJ pipeline ensures no one can trace redactions, preserving opacity.""",
    "dual": """Focusing on the dual-layer redaction: The FBI pre-redacted key files before DOJ review, as Rep. Khanna stated. This creates a partitioned system where blame can be shifted, making oversight impossible. It's designed for plausible deniability, protecting elite actors while claiming investigative norms.""",
    "conclusion": """This analysis reveals a pattern of protection spanning administrations. We need real reforms for transparency and justice. Thanks for watching – share your thoughts and demand accountability.""",
}
