"""
Narration script for: types-of-infinity
Generated: 2026-02-13
Duration: ~3.5 minutes
"""

SCRIPT = {
    "intro": """Welcome to our exploration of infinity. We all have an intuitive sense of infinity as something endless, something that goes on forever. But in mathematics, infinity isn't just a vague idea—it's a rich and fascinating concept with different types and layers. From the countable infinities we can list out to the vast uncountable infinities that defy enumeration, infinity comes in many forms. Let's dive into the world of mathematical infinity and discover its surprising depths.""",
    "countable": """Let's start with countable infinity. Think of the natural numbers: 1, 2, 3, and so on, forever. This set is infinite, but it's countable—you can list them all out in order. We say it's countably infinite, with the cardinality of aleph-zero. Any set that can be paired up with the natural numbers through a bijection is countable. This includes the integers, rational numbers, and even some infinite sets that might surprise you.""",
    "uncountable": """Now, step up to uncountable infinity. The real numbers between 0 and 1—those decimal expansions that go on forever—are uncountably infinite. Georg Cantor proved this with his diagonalization argument: imagine listing all real numbers, then constructing a new number that differs from each one in every decimal place. This new number can't be in your list, proving there are more real numbers than natural numbers. This is the continuum, a larger infinity than countable infinity.""",
    "cardinals": """Enter the world of cardinal numbers, which measure the sizes of infinite sets. Aleph-zero is the smallest infinity, the size of countable sets. Aleph-one is the next size up, equal to the continuum under the continuum hypothesis. But is the continuum hypothesis true? That's one of mathematics' greatest unsolved questions. Cardinal arithmetic lets us add, multiply, and compare these infinities, revealing that some operations preserve size while others create larger infinities.""",
    "ordinals": """Beyond cardinals lie the ordinal numbers, which capture the idea of order and well-ordering. While cardinals tell us how many elements are in a set, ordinals describe the structure of infinite sequences. Omega is the first infinite ordinal, followed by omega plus one, and on to epsilon-zero and beyond. Ordinals help us understand infinite processes and the foundations of set theory, showing that infinity has not just size, but structure and sequence.""",
    "paradoxes": """Infinity brings paradoxes that challenge our intuition. Consider Hilbert's Hotel: a hotel with infinitely many rooms, all occupied. Yet when a new guest arrives, the manager moves everyone to room n+1, freeing up room 1. Even an infinite bus of guests can be accommodated! In the real world, infinity appears in geometric series, fractals, and even in the foundations of calculus. These concepts show how infinity isn't just abstract—it's essential to understanding our universe.""",
    "conclusion": """We've journeyed through the types of infinity: from countable to uncountable, cardinals to ordinals, and even the paradoxes that infinity creates. Infinity isn't a single concept but a spectrum of mathematical ideas, each revealing new layers of understanding. As Cantor showed, there are infinities of different sizes, challenging our fundamental notions of quantity and completeness. Infinity continues to inspire mathematicians and philosophers alike, reminding us that some questions remain eternally open.""",
}
