"""
Narration script for: Climate Models and the Signal-to-Noise Paradox
Generated: 2026-02-11
Duration: ~200 seconds
"""

SCRIPT = {
    "intro": "Climate models systematically fail not because they get the physics of CO2 wrong in isolation, but because the ratio of their internally-generated noise to the real atmosphere's noise is inverted: models produce too much unpredictable variability relative to forced signal, yet the real atmosphere appears more predictable than models say it should be, which means models are misallocating energy between the forced response pathway and the internal variability pathway, and that misallocation is concentrated in how they handle the vertical redistribution of latent heat in the tropics.",
    "paradox": "The standard framing treats the model-observation warming gap as a problem of sensitivity being too high. But the signal-to-noise paradox discovered in seasonal-to-decadal forecasting reveals something structurally different: models can predict the pattern of observed variability, like the NAO, with correlation around 0.6, yet their own ensemble members correlate with each other at only around 0.2, meaning the real atmosphere is roughly three times more predictable than models say it should be.",
    "sensitivity": "This paradox cannot be explained by simple sensitivity tuning. If models merely had ECS set too high, they would overpredict both the forced trend AND the amplitude of the predictable signal. Instead, they overpredict the trend while underpredicting the amplitude of predictable modes by a factor of roughly 3.",
    "mechanism": "The mechanism is almost certainly in convective heat redistribution. Roy Spencer's January 2026 analysis confirms all 39 CMIP6 models overpredict tropical tropospheric warming trends versus three independent observational classes. Spencer identifies excessive positive water vapor feedback as the likely cause. But coupling this with the signal-to-noise paradox yields a sharper diagnosis: the models' convective parameterizations are converting too much surface energy into disorganized internal variability, that is noise, and too little into coherent forced response, the reverse of what the real tropical atmosphere does.",
    "implications": "This implies that improving convective parameterization would simultaneously close the tropical hotspot gap AND resolve the signal-to-noise paradox, because both stem from the same energetic misallocation. No one in the literature has explicitly connected these two anomalies as symptoms of a single underlying error.",
    "prediction": "The falsifiable prediction: any climate model that resolves the signal-to-noise paradox for the winter NAO, bringing ensemble-member cross-correlation up to match the model-observation correlation, will, without any additional tuning, also reduce its tropical tropospheric warming bias by at least 40%. Conversely, if a model closes the tropical hotspot gap through ECS reduction alone but retains the signal-to-noise paradox, it has not fixed the underlying problem and will fail at a different diagnostic.",
    "disproof": "This would be disproven if a model is found that resolves the signal-to-noise paradox while retaining the full tropical hotspot bias, or vice versa, because that would show the two anomalies are independent.",
}
