"""
Narration script for: 123-test
Generated: 2026-02-13
Duration: ~180 seconds
"""

SCRIPT = {
    "intro": """Have you ever noticed how the spiral patterns in pinecones or the arrangement of leaves on a stem seem to follow a mysterious mathematical order? Welcome to the fascinating world of the Fibonacci sequence. This simple pattern of numbers appears everywhere in nature, from the petals on a flower to the structure of galaxies. Today, we'll explore what the Fibonacci sequence is, its remarkable properties, and why it keeps showing up in the world around us.""",
    "definition": """The Fibonacci sequence is named after the Italian mathematician Leonardo Fibonacci, who introduced it to the Western world in 1202. It starts with the numbers 0 and 1, and each subsequent number is the sum of the two preceding ones. So after 0 and 1, we get 1, then 2, then 3, then 5, then 8, and so on. Let me show you the sequence: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, and it continues infinitely.""",
    "properties": """One of the most amazing properties of the Fibonacci sequence is its connection to the golden ratio. If you take the ratio of consecutive Fibonacci numbers, like 8 divided by 5 or 13 divided by 8, you get approximately 1.618, which is the golden ratio. As you go further in the sequence, this ratio approaches the golden ratio more precisely. The Fibonacci sequence also has other interesting properties. Every third number is even, and you can find Fibonacci numbers in Pascal's triangle. These patterns reveal deep mathematical relationships that have captivated mathematicians for centuries.""",
    "applications": """The Fibonacci sequence isn't just a mathematical curiosity—it appears throughout nature and human creations. In botany, you'll find Fibonacci numbers in the number of petals on flowers, like 3 on a lily, 5 on a buttercup, or 8 on a delphinium. Pinecones and pineapples show spiral patterns based on Fibonacci numbers. In architecture and art, the golden ratio derived from Fibonacci appears in the Parthenon, the Mona Lisa, and modern designs. Even in technology, Fibonacci numbers help with algorithms for computer science and data structures. This sequence bridges pure mathematics with the real world in beautiful and unexpected ways.""",
    "recap": """To recap, the Fibonacci sequence starts with 0 and 1, where each number is the sum of the previous two. It connects to the golden ratio and appears in nature's patterns, from flower petals to spiral galaxies. Its mathematical properties and real-world applications make it one of the most intriguing sequences in mathematics. Whether you're a mathematician, scientist, or just curious about patterns, the Fibonacci sequence reminds us of the hidden order in the universe.""",
}
