"""
Narration script for: polytope-efficiency
Generated: 2026-02-13
Duration: ~240 seconds (estimated)
Total words: ~600 (estimated)
"""

SCRIPT = {
    "intro": """Imagine a world where more eyes don't mean better vision. Humans see with just three types of color receptors, yet we discriminate over a hundred hues. Mantis shrimp have twelve receptors, but only distinguish about twelve colors. This paradox hides a deeper truth about perception. Today, we'll explore perceptual efficiency—a metric that measures how many discriminable experiences an organism extracts from its available experiential complexity. We'll use the Markov polytope from consciousness theory to quantify this, revealing why adding more receptors often leads to coarser, not richer, perception.""",
    "problem": """Let's dive into the color dimension problem. Humans, with our three cone types, achieve around 130 spectrally discriminable hue steps across the visible spectrum. Mantis shrimp, despite having twelve narrowly tuned photoreceptor classes spanning 300 to 720 nanometers, discriminate roughly twelve spectral bins. That's a factor of ten fewer discriminations despite four times more receptors. The standard explanation is a dichotomy between opponent processing and interval decoding. Primates like us build rich color spaces through deep, recurrent cortical refinement. Mantis shrimp use a shallow, hard-wired winner-take-all strategy, where color perception corresponds to whichever receptor fires most strongly.""",
    "polytope": """To understand this, we turn to Hoffman, Prakash, and Prentner's conscious-agent formalism. They define a conscious agent as a six-tuple including perception, decision, and action kernels. The qualia kernel captures complete experiential dynamics as a Markov chain transition matrix. For an agent with n qualitative experiential states, all possible qualia kernels form a convex polytope called the Markov polytope, with dimension n times n minus n. This polytope represents the geometric arena of all possible experiential dynamics. A kernel flow describes how an agent's dynamics evolve, potentially converging toward a fusion simplex where all states become indistinguishable. The polytope dimension measures the total degrees of freedom available for consciousness.""",
    "metric": """Now we define perceptual efficiency. Let k be the number of functionally independent photoreceptor classes. The Markov polytope dimension is D equals k times k minus k. B measures the total spectral just-noticeable-difference hue steps, integrated across the organism's visible spectrum. Perceptual efficiency eta equals B divided by D—how many discriminable experiences per unit of polytope dimension. High eta means the organism extracts many more distinctions than the raw polytope suggests, through deep neural processing. Low eta means many degrees of freedom go unexploited. Near eta of one marks a transition where exploiting additional dimensions costs more than it's worth. This connects directly to polytope geometry, where full opponent processing uses half the available dimensions.""",
    "data": """Let's look at the empirical data across six species. Dogs with two receptors achieve about 20 JNDs for an eta of 10. Honeybees with three receptors get 40 JNDs, eta 6.7. Humans hit 130 JNDs, eta 21.7. Pigeons with five receptors reach 100 JNDs, eta 5. Butterflies with four get 150 JNDs, eta 12.5. But mantis shrimp with twelve receptors only manage 12 JNDs, eta 0.09. A log-log regression shows eta scales as k to the power of negative 2.83, with R-squared about 0.78. This inverse relationship reveals a fundamental trade-off: more receptors without deeper processing leads to coarser perception. The mantis shrimp outlier drives the fit, while humans sit above the line, suggesting exceptional cortical amplification.""",
    "regimes": """This data reveals two regimes of color processing. Regime one is cortical amplification for high eta, typically k less than or equal to four. Deep, recurrent neural processing transforms broad spectral samples into fine discrimination. Primates subdivide their low-dimensional polytope into a fine mesh. Regime two is interval decoding for low eta, k greater than six. Shallow, hard-wired winner-take-all processing collapses onto low-dimensional faces of the polytope. This suits organisms needing rapid decisions with small nervous systems. The transition stems from a resource mismatch: polytope dimension grows quadratically with k, while neural resources grow at best linearly. When k is small, the cost is manageable. When large, organisms abandon depth for breadth.""",
    "predictions": """Our framework yields falsifiable predictions. First, across taxa, eta will show significant inverse scaling with k. High-k organisms will cluster at eta less than two. Second, human tetrachromats will show elevated JNDs but eta no higher than 16.7, lower than trichromats despite gains. Third, weak tetrachromats will have B indistinguishable from trichromats, but eta halved when scored against k equals four. Fourth, for synthetic sensors, adding channels beyond eta less than one won't improve fine discrimination unless processing scales quadratically. These predictions bridge consciousness theory with sensory ecology, offering new ways to test the Markov polytope's relevance to real perception.""",
    "conclusion": """The perceptual efficiency metric eta equals B over k times k minus k provides a dimensionless bridge between abstract consciousness theory and concrete sensory biology. The strong inverse scaling of eta with receptor count supports the polytope compression hypothesis: adding sensory channels without deepening processing collapses experience into coarser regimes. If the Markov polytope is truly the arena of consciousness, as Hoffman proposes, then eta measures how much of that arena organisms actually occupy. This framework not only explains color vision paradoxes but offers a quantitative probe into the geometry of experience itself.""",
}
