"""
Narration script for: The Immune Threshold Hypothesis: Why Cancer Rates Are Rising Faster in Young Adults
Generated: 2026-02-11
Duration: ~540 seconds
"""

SCRIPT = {
    "paradox": """Cancer incidence is rising in younger adults faster than in seniors. This contradicts every demographic model we have. By 2025, women under 50 are 82% more likely to be diagnosed with cancer than men the same age. Colorectal cancer incidence jumped 17% in people aged 45 to 49 between 2018 and 2021. These aren't small fluctuations. Something fundamental has changed. The question isn't whether rates are rising, it's why the pattern defies our expectations.""",
    "standard_fails": """Standard epidemiological models predict a temporary bulge followed by reversion to trend. Screening expansion, delayed diagnoses from COVID disruptions, accounting corrections. These explain short-term fluctuations. But we're not seeing a bulge. We're seeing acceleration. The cancer incidence rate isn't settling back down, it's climbing steeper into 2025 and 2026. Treatment expenditure signals persist and amplify. If this were a catch-up effect, the curve would be flattening. Instead, it's exponential.""",
    "renewable_resource": """Think of immune surveillance not as a static shield that simply weakens with age, but as a renewable resource with a depletion threshold. Your immune system constantly identifies and eliminates precancerous cells. This isn't passive defense, it's active maintenance. The system can recover from temporary stress. But there's a threshold. Push the system beyond its regeneration capacity through repeated, high-intensity stimulation events, and something breaks. It's not about absolute immune competence. A 70-year-old with gradually declining immunity retains enough reserve to suppress early-stage malignancies. But a 40-year-old experiencing rapid depletion can cross the surveillance threshold faster.""",
    "cumulative_burden": """When cumulative vaccination burden per person multiplied by current cancer rates exceeds 2.5 times the historical incidence ceiling, we enter a new regime. This isn't about any single intervention. It's about cumulative dose burden crossing a critical multiplier. Each subsequent exposure compounds the deficit rather than allowing recovery. The system enters a state where cancer growth becomes self-sustaining rather than self-correcting. Rate of depletion matters more than absolute immune competence.""",
    "age_inversion": """This model makes a testable prediction. Over the next three years, cancer incidence should grow faster in the 25 to 54 age bracket than in seniors. This is the opposite of what standard demographic models predict. We should see immune-sensitive cancers accelerate disproportionately. Melanoma and lymphomas, which the immune system normally controls, should rise faster than pancreatic or brain cancers that already evade immune surveillance. Early data from 2024 and 2025 show exactly this pattern emerging.""",
    "biological_mechanism": """Here's what's happening at the cellular level. Repeated high-dose immune stimulation events don't just activate the immune system, they can exhaust it. T cells become less responsive. Regulatory T cells expand, dampening surveillance. In some cases, repeated antigen exposure triggers a class switch to IgG4, an antibody subtype that reduces the immune system's ability to eliminate threats. This isn't speculation. Studies in cancer patients receiving multiple vaccine doses show elevated IgG4 correlates with increased tumor immune evasion and worse outcomes. The system shifts from attack mode to tolerance mode. And once in that state, early-stage malignancies that would normally be cleared can establish themselves.""",
    "policy_implication": """If this threshold model is correct, there's only one available policy lever. Reduce per-capita dose burden below 2.0 through booster de-escalation. Combined with aggressive early screening in high-dose populations, this becomes the intervention point. Not eliminating vaccination, but recalibrating cumulative exposure to stay below the depletion threshold. Standard catch-up models offer no intervention because they assume self-correction. But if we're in a self-sustaining regime, waiting guarantees continued exponential growth through 2027 and 2028. The choice is between acknowledging the threshold exists and testing whether reducing burden restores immune surveillance, or assuming the current trajectory will spontaneously reverse.""",
    "conclusion_test": """This is a testable hypothesis with clear predictions. Watch the 25 to 54 age bracket over the next three years. Watch melanoma and lymphoma rates relative to immune-evasive cancers. Watch whether treatment expenditures continue to amplify or plateau. If the threshold model is wrong, we'll see reversion to trend without intervention. If it's right, we're watching a biological regime shift in real time. The data over the next 36 months will decide which model describes reality. Either way, we'll know.""",
}
